version: '2'

services:

  master:
    image: eugenekozyrev/repo:greenplum-5.10.1-orca-py2
    ports:
      - 5432:5432
    depends_on:
      - segment-1
      - segment-2
    links: 
      - segment-1
      - segment-2
    volumes:
      - ./gpdata:/gpdata

  segment-1:
    image: eugenekozyrev/repo:greenplum-5.10.1-orca-py2
    entrypoint: "gpdb-seg-entrypoint.sh"
    volumes:
      - ./gpdata:/gpdata

  segment-2:
    image: eugenekozyrev/repo:greenplum-5.10.1-orca-py2
    entrypoint: "gpdb-seg-entrypoint.sh"
    volumes:
      - ./gpdata:/gpdata

volumes: 
  gpdata:

# docker-compose up -d